version: '3'
services:
  webfm:
    container_name: web_fm
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8090:8090"
    tty: true
    volumes:
      - ./data:/webfm/data
    # environment: 
    #   - SUBJECTS_DIR=/data/derivatives/freesurfer
    #   - SUBJECT=PY20N007
    #   - PORT=5000


