version: '3'
services:
    webfm:
        # container_name: web_fm
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - '8564:8564'
        environment:
            - dataDir=/webfm/data
            - PORT=8564
        # volumes:
        #     - /mnt/user/Data/Projects/Work/webfm:/webfm
        tty: true
