#!/usr/bin/env python3


## IMPORTS

# Core
import argparse
import os.path

# Custom
import webfm.export


## HELPERS

def _make_parser():

    parser = argparse.ArgumentParser()

    parser.add_argument( '-s', '--subject',
                         help = 'Subject identifier' )

    parser.add_argument( '-b', '--brain',
                         help = 'Location of brain image file' )

    parser.add_argument( '-m', '--montage',
                         help = 'Location of montage CSV file' )

    parser.add_argument( '-o', '--output',
                         help = 'Location to save output metadata',
                         default = './.metadata' )

    return parser


## MAIN

def main():
    args = _make_parser().parse_args()

    # Deduce metadata

    metadata = {}

    if 'subject' in args:
        metadata['subject'] = args.subject
    else:
        metadata['subject'] = input( 'Subject ID: ' )

    if 'brain' in args:
        brain_path = os.path.abspath( os.path.expanduser( args.brain ) )
        metadata['brainImage'] = webfm.export._preprocess_image( brain_path )

    if 'montage' in args:
        montage_path = os.path.abspath( os.path.expanduser( args.montage ) )
        metadata['sensorGeometry'] = webfm.export._preprocess_sensor_geometry( montage_path )

    # Write result

    output_path = os.path.abspath( os.path.expanduser( args.output ) )
    with open( output_path, 'w' ) as output_file:
        webfm.export.write_metadata( output_file, metadata )


## ENTRY

if __name__ == '__main__':
    main()


#