#!/usr/bin/env python3


## IMPORTS

# Core
import sys
import json

# Numerics
import numpy        as np
import scipy.signal as sig


## MAIN

def main():

    # TODO THIS SHOUL NOT BE HARDCODE BAD BAD
    fs          = 1000

    # Magic numbers
    hg_band     = [70.0, 110.0]
    nperseg     = 128
    nskip       = 20
    noverlap    = nperseg - nskip

    # Read and parse data
    in_data = None
    try:
        in_data = json.load( sys.stdin )
    except Exception as e:
        print( e )
        return 1

    # Process data
    out_data = {}
    for ch, ch_signal in in_data.items():
        # average_t . log . FFT
        f, t, s = sig.spectrogram( ch_signal,
                                   nperseg = nperseg,
                                   noverlap = noverlap )
        hg_indices = np.where( np.logical_and( f >= hg_band[0], f <= hg_band[1] ) )[0]
        out_data[ch] = np.mean( np.log( s[hg_indices, :] ),
                                axis = 0 )

    # Print output data
    print( json.dumps( out_data ) )
    return 0


## ENTRY

if __name__ == '__main__':
    main()


#