#!/usr/bin/env python3


## IMPORTS

# Core
import sys
import json

# Numerics
import numpy as np


## MAIN

def main():

    in_data = None

    # Read and parse data
    try:
        in_data = json.load( sys.stdin )
    except Exception as e:
        print( e )
        return 1

    # Fake processing of data
    out_data = {}
    for channel, v in in_data.items():
        values = np.array( v )
        processed = 1.0 * values
        out_data[channel] = processed.tolist()

    # Print output data
    print( json.dumps( out_data ) )
    return 0


## ENTRY

if __name__ == '__main__':
    main()


#